server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: prod

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

mybatis-plus:
  type-aliases-package: cc.mrbird.febs.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty


logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            metadata:
              TableInfoHelper: error
mybatis:
  configuration:
    map-underscore-to-camel-case: true

